name: iq_test
description: A Flutter IQ Test App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  flutter_animate: ^4.1.1
  video_player: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/background.mp4
    - assets/sounds/click.mp3
    - assets/sounds/answer_click.mp3
    - assets/sounds/toggle.mp3
    - assets/sounds/back.mp3
    - assets/sounds/restart.mp3
    - assets/sounds/language_select.mp3